---
- name: Restart Zookeeper
  systemd:
    daemon_reload: true
    name: "{{zookeeper_service_name}}"
    state: restarted
  when:
    - not nonroot_deployment|bool
  tags:
    - systemd

- name: (Non-root deployment) Stop zookeeper
  shell: "{{ script_path }}/zookeeper_stop.sh"
  when: nonroot_deployment|bool

- name: Startup Delay
  wait_for:
    timeout: "{{ zookeeper_health_check_delay }}"

- name: (Non-root deployment) Start zookeeper
  shell: "{{ script_path }}/zookeeper_start.sh"
  when: nonroot_deployment|bool