---
- name: Restart Kafka
  systemd:
    daemon_reload: true
    name: "{{kafka_broker_service_name}}"
    state: restarted
  tags:
    - systemd

- name: (Non-root deployment) Stop Kafka
  shell: "{{ script_path }}/kafka_broker_stop.sh"
  when: nonroot_deployment|bool

- name: Startup Delay
  wait_for:
    timeout: "{{ kafka_broker_health_check_delay }}"

- name: (Non-root deployment) Start Kafka
  shell: "{{ script_path }}/kafka_broker_start.sh"
  when: nonroot_deployment|bool