---
- name: restart kafka
  include_tasks: tasks/restart_and_wait.yml
  when:
    - not kafka_broker_skip_restarts
  tags:
    - systemd

- name: (Non-root deployment) restart kafka
  include_tasks: tasks/restart_and_wait_script.yml
  when:
    - not kafka_broker_skip_restarts
    - nonroot_deployment|bool