---
- name: (Non-root deployment) Stop Control Center
  shell: "{{ script_path }}/control_center_stop.sh"
  when: nonroot_deployment|bool

- name: Startup Delay
  wait_for:
    timeout: "{{ control_center_health_check_delay }}"

- name: (Non-root deployment) Start Control Center
  shell: "{{ script_path }}/control_center_start.sh"
  when: nonroot_deployment|bool