---
- name: Restart Kafka Connect
  systemd:
    daemon_reload: true
    name: "{{kafka_connect_service_name}}"
    state: restarted
  when: 
    - not nonroot_deployment|bool
  tags:
    - systemd

- name: (Non-root deployment) Stop Kafka Connect
  shell: "{{ script_path }}/kafka_connect_stop.sh"
  when: nonroot_deployment|bool

- name: Startup Delay
  wait_for:
    timeout: "{{ kafka_connect_health_check_delay }}"

- name: (Non-root deployment) Start Kafka Connect
  shell: "{{ script_path }}/kafka_connect_start.sh"
  when: nonroot_deployment|bool